#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain () {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomain="www lb-01 web-01 web-02"
    fi

    for sub in $subdomain; do
        record=$(dig +short "$sub.$domain" | head -n1)
        if [ -n "$record" ]; then
            echo "The subdomain $sub is a $(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}') record and points to $record"
        else
            echo "Subdomain $sub does not exist or is not configured for $domain"
        fi
    done
}

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain_name> [subdomain_name]"
    exit 1
fi

domain="$1"
subdomain="$2"

print_domain_subdomain "$domain" "$subdomain"

